// Generated by CoffeeScript 1.3.3
(function() {
  var ldap;

  ldap = require('ldapjs');

  module.exports = {
    start_server: function() {
      var server;
      server = ldap.createServer();
      return server.listen(1389, function() {
        return console.log('LDAP server is up at: %s', server.url);
      });
    }
  };

}).call(this);
