// Generated by CoffeeScript 1.3.3
(function() {
  var app, express;

  express = require('express');

  app = express();

  module.exports = {
    start_server: function() {
      this.setup_routes();
      app.listen('3000');
      return console.log("Webserver is up at: http://0.0.0.0:%s", 3000);
    },
    setup_routes: function() {
      return app.get('/', function(req, res) {
        return res.send('Hello world');
      });
    }
  };

}).call(this);
