// Generated by CoffeeScript 1.3.1
(function() {
  var app, express;

  express = require('express');

  app = express();

  module.exports = {
    start_server: function() {
      this.setup_routes();
      return app.listen('3000');
    },
    setup_routes: function() {
      return app.get('/', function(req, res) {
        return res.send('Hello world');
      });
    }
  };

}).call(this);
