// Generated by CoffeeScript 1.3.3
(function() {
  var app, common, restify;

  common = require('./common');

  restify = require('restify');

  app = restify.createServer();

  module.exports = {
    start_server: function(info) {
      this.setup_routes(info);
      app.listen('3000');
      return console.log("Webserver is up at: http://0.0.0.0:%s", 3000);
    },
    setup_routes: function(info) {
      return app.get('/', function(req, res) {
        return res.json(200, {
          name: info.name,
          identity: info.identity,
          version: info.version
        });
      });
    }
  };

}).call(this);
